#
# Genomon Project information
#
# Mandatory definitions
#   project
#   sample_name
#   sample_date1
project:                genomon_test
sample_name:            mimorin
sample_date:            20140930


#
# Data directory
#
# Mandatory definitions
#   project_root
#
# Optional
#   project_dir_tree
#
project_root:               /home/eigos/Data/GenomonProj
project_dir_tree:
    project_directory:
        data:
            sample_date:
                sample_name
        results:
            run_date:
                sample_date_sample_name:
                    - config
                    - script
                    - log
                    - out:
                        - fastq
                        - bam
                        - annovar
                        - fisher
                        - cnv
                        - fusion
                        - sv
#
# Input files
#
# Mandatory definitions
#   input_file_dir
#   iput_file_type
#   file_name
#
# Optional
#   file_ext ( we assume that input file extion is either '.fastq' or '.bam',
#              if the extension is other than those two, need to specify. )
#
#   pair_id  ( if file_name includes pair_id, need to specify )
#
#   sample_subdir ( if the input_file_dir includes sub-directories containting data files,
#                   you can specify )
#
# Wild cards (*, ?) are allowed in file_name, sample_subdir.
#
input_file_dir:             /home/mimorin/genomon/data/input/140930_CRC_target_barcode
input_file_type:            paired_fastq # paired_fastq,  single_fastq, paired_bam, single_bam
file_name:                  R{pair_id}.fastq.filt
file_ext:                   .fastq.filt
pair_id:
                            - 1
                            - 2
sample_subdir:              s_B1N

#bed_files:                  None # for Panel


#
# Analysis
#
tasks:
                    WGS:
                        - split_fastq
                        - bwa_mem
                        - merge_bam

#
# Split fastq file into multiple files with line number specified below.
#
split_fastq_line_number:    1000000

# tasks type
#                    WGS:
#                        - bamtofastq
#                        - split_fastq
#                        - cutadapt
#                        - bwa_mem
#                        - merge_bam
#                        - markduplicate
#                        - mutation_call
#                    WES:
#                        - bamtofastq
#                        - split_fastq
#                        - cutadapt
#                        - bwa_mem
#                        - merge_bam
#                        - markduplicate
#                        - mutation_call
#                    Capture:
#                        - bamtofastq
#                        - split_fastq
#                        - cutadapt
#                        - bwa_mem
#                        - merge_bam
#                        - markduplicate
#                        - mutation_call
#                    RNA-Anders:
#                        - start
#                        - hiseq
#                        - desq2
#                    RNA-Tuxedo:
#                        - tophat
#                        - cufflinks
#                        - cuffmerge
#                        - cuffmerge
#                        - cuffdiff
#                        - cummerbund
#                    CNV:
#                    SV:
#                    Fusion:

#
# Analysis parameters
#
adaptor:
                        - NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
                        - NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
base_quality_cutoff:    15
mapq_cutoff:            30
max_indel:              2

#
# Job control
#
job_type:
                    bam2fastq:              sjob
                    split_fastq:            sjob
                    cutadapt:               sjob
                    bwa_mem:                sjob
                    merge_bam:              sjob
                    fisher_mutation_call:   sjob
                    ebcall_mutation_call:   sjob
                    copy_number:            sjob
                    sv:                     sjob

memory:
                    split_fastq:            2G
                    cutadapt:               2G
                    bwa_mem:                8G
                    merge_bam:              4G
                    fisher_mutation_call:   2G
                    ebcall_mutation_call:   4G
                    copy_number:            4G
                    sv:                     8G

#
# qsub command format
#
# allowd parameters:
#   job_type    Genomon uses the value specified in job_type section.
#   s_vmem      Genomon uses the value specified in memory section.
#   mem_req     Genomon uses the value specified in memory section.
#   cmd         Shell script file to run
#
qsub_cmd: "qsub -sync yes -now no -l {job_type},s_vmem={s_vmem},mem_req={mem_req} {cmd}"

