#! /usr/bin/env python

# from main import run
import argparse

parser = argparse.ArgumentParser(prog = "genomon_pipeline")

parser.add_argument("--version", action = "version", version = "fusionfusion-2.0.0")

parser.add_argument('analysis_type', choices=['dna', 'rna'],
                    help = "analysis type")

parser.add_argument("input_file_list", metavar = "input.txt", default = None, type = str,
                    help = "input sample list flie [csv/tsv/xlsx]")

parser.add_argument("output_root", metavar = "output_dir", default = None, type = str,
                    help = "output root directory")

parser.add_argument( '-s', "--config_file",  help = "Genomon pipeline configuration file",      type = str )
parser.add_argument( '-f', "--job_file",     help = "Genomon pipeline job configuration file",  type = str )
parser.add_argument( '-p', "--param_file",   help = "Genomon pipeline analysis parameter file", type = str )

args = parser.parse_args()

# main.run(args)
