#!/usr/bin/python
"""

Genome Analysis Pipeline


"""

import sys
import os
import shutil
from datetime import datetime
import argparse
from glob import glob
from ruffus import *
import yaml

################################################################################
#
# Globals
#
log = None
global Geno
class Geno(object):
    now     = None
    options = None
    conf    = None
    job     = None
    dir     = {}
    RT      = None


################################################################################
#
# Private modules
#
import genomon_rc as res
from genomon_cfg import genomon_config as ge_cfg
from genomon_job import genomon_job as ge_job
from runtask import RunTask

################################################################################
#
# Subroutines
#
def construct_arguments( ):
    """
    Call argparse and create argument object
    
    """

    parser = cmdline.get_argparse( description='Genome Analysis Pipeline' )

    ge_arg = parser.add_argument_group( 'genomon', 'Genomon options' );

    ge_arg.add_argument( '-s', "--config_file",  help = "Genomon pipeline configuration file",    type = str )
    ge_arg.add_argument( '-f', "--job_file",     help = "Genomon pipeline job file",              type = str )
    ge_arg.add_argument( '-m', "--mpi",          help = "Enable MPI",   action ='store_true',     default = False )
    ge_arg.add_argument( '-l', "--fullpath",     help = "Use full path in scripts",   action ='store_true',     default = False )

    return parser

########################################
def printheader( myself, options ):
    """
    Print infomration about this run

    """
    Geno.now = datetime.now()

    log.info( "Generated by {my}".format(my = myself ) )
    log.info( "Input config file = {input}".format( input = options.config_file  ) )
    log.info( "Input job file    = {input}".format( input = options.job_file  ) )


########################################
def replace_reserved_string( dir_tmp, cwd ):
    """
    Reserved names to replace strings defined in job configuration file
        project_directory   -> defined as project in job configuration file
        data_date           -> defined sample_date in job configuration file
        sample_name         -> defined sample_name in job configuration file
        run_date            -> date of the pipeline to run
    """
    #
    # Replace reserved strings
    #
    dir_replace = None
    if dir_tmp == 'project_directory':
        dir_replace = Geno.job.get( 'project' )
    elif dir_tmp == 'data_date':
        dir_replace = str( Geno.job.get( 'sample_date' ) )
    elif dir_tmp == 'sample_name':
        dir_replace = Geno.job.get( 'sample_name' )
    elif dir_tmp == 'data_date_sample_name':
        dir_replace = str( Geno.job.get( 'sample_date' ) ) + '_' + Geno.job.get( 'sample_name' )
    elif dir_tmp == 'run_date':
        dir_replace = res.date_format.format( 
                    year = Geno.now.year, 
                    month = Geno.now.month, 
                    day = Geno.now.day ) 
    else:
        dir_replace = dir_tmp
    
    return dir_replace

def make_dir( dir ):
    if not os.path.exists( dir ):
        os.makedirs( dir )
    return dir

def get_dir ( dir_tree, cwd, dir_name ):
    """
    return the path to the specified directory by dir_tree

    """
    if isinstance( dir_tree, dict ):
        for dir_tmp in dir_tree.keys():
            dir_replace = replace_reserved_string( dir_tmp, cwd )
            cwd_tmp = cwd + '/' + dir_replace
            if isinstance( dir_tmp, str) and dir_tmp  == dir_name:
                return cwd_tmp
            if ( isinstance( dir_tree[ dir_tmp ], dict ) or
                 isinstance( dir_tree[ dir_tmp ], list ) ):
                dir_returned =  get_dir( dir_tree[ dir_tmp ], cwd_tmp, dir_name  )

                if None != dir_returned:
                    return dir_returned
            
    elif isinstance( dir_tree, list ):
        n = 0
        for dir_tmp in dir_tree:
            if isinstance( dir_tmp, str):
                dir_replace = replace_reserved_string( dir_tmp , cwd )
                cwd_tmp = cwd + '/' + dir_replace
            elif isinstance( dir_tmp, dict):
                dir_replace = replace_reserved_string( dir_tmp.keys()[ 0 ] , cwd )
                cwd_tmp = cwd + '/' + dir_replace

            if ( ( isinstance( dir_tmp, str) and dir_tmp == dir_name ) or
                 ( isinstance( dir_tmp, dict) and dir_tmp.keys()[0] == dir_name ) ):
                return cwd_tmp
            else:
                if ( isinstance( dir_tree[ n ], dict ) or
                     isinstance( dir_tree[ n ], list ) ):
                    dir_returned =  get_dir( dir_tree[ n ], cwd, dir_name )
                    if None != dir_returned:
                        return dir_returned
            n = n + 1
    else:
        if isinstance( dir_tmp, str) and dir_tmp  == dir_name:
            dir_replace = replace_reserved_string( dir_tmp, cwd )
            cwd_tmp = cwd + '/' + dir_replace
            return cwd_tmp

    return None


def make_directories( ):
    """
    Make Directory Tree Structure
       Read directory structure from resource file
       Make sure that input data exists.
       Create results directory if necesesary

    """

    #
    # Make sure the input data is availalbe.
    #
    

    error_message = ''
    try:
        if not os.path.exists( Geno.job.get( 'project_root' )):
            log.error( "Dir: {dir} not found.".format( dir = Geno.job.get( 'project_root' ) ) )
            raise


        #
        # make directories
        #
        dir_tree = yaml.load( res.dir_tree_resource )

        #
        # get directory locations
        #
        cwd = Geno.job.get( 'project_root' )
        if not Geno.options.fullpath:
            os.chdir( cwd )
            cwd = '.'

        for target_dir in res.end_dir_list:
            Geno.dir[ target_dir ] = get_dir( dir_tree, cwd, target_dir )
            make_dir( Geno.dir[ target_dir ] )

        #
        # make sure that data exists
        #
        Geno.dir[ 'data' ] = "{data}/{sample_date}/{sample_name}". format(
                                data = get_dir( dir_tree, cwd, 'data' ),
                                sample_date = Geno.job.get( 'sample_date' ),
                                sample_name = Geno.job.get( 'sample_name' ) )
        if not os.path.exists( Geno.dir[ 'data' ] ):
            log.error( "Dir: {dir} not found.".format( dir = Geno.dir[ 'data' ] ) )
            raise

    except IOError as (errno, strerror):
        log.error( "make_directories failed." )
        log.error( "IOError {0}]{1}".format( errno, strerror ) )
    except:
        log.error( "make_directories failed." )
        log.error( "Unexpected error: {1}".format( error_message ) )

########################################
def copy_config_files():
    """
    Copy genomon system configuration file and job configuration file
    to results directory

    """
    global Geno

    config_dir = Geno.dir[ 'config' ]

    src = Geno.options.config_file
    basename = os.path.splitext( os.path.basename( src ) )[ 0 ]
    ext = os.path.splitext( os.path.basename( src ) )[ 1 ]
    config_backup = res.file_timestamp_format.format(
                                        name=basename,
                                        year=Geno.now.year,
                                        month=Geno.now.month,
                                        day=Geno.now.day,
                                        hour=Geno.now.hour,
                                        min=Geno.now.minute,
                                        msecond=Geno.now.microsecond )
    dest = "{dir}/{basename}{ext}".format( dir = config_dir,
                                            basename = config_backup,
                                            ext = ext )
    shutil.copyfile( src, dest )

    src = Geno.options.job_file
    basename = os.path.splitext( os.path.basename( src ) )[ 0 ]
    ext = os.path.splitext( os.path.basename( src ) )[ 1 ]
    dest = "{dir}/{basename}{ext}".format( dir = config_dir,
                                            basename = config_backup,
                                            ext = ext )
    shutil.copyfile( src, dest )

###############################################################################
#
# main
#
def main():
    global starting_files
    global log
    global Geno

    try:
        #
        # Argument parse
        #
        argvs = sys.argv
        arg_parser = construct_arguments()

        if len(argvs) < 3:
            arg_parser.print_help()
            raise

        Geno.options = arg_parser.parse_args()

        #
        # Logging setup
        #
        #  logger which can be passed to multiprocessing ruffus tasks
        log, log_mutex = cmdline.setup_logging( __name__,
                                                Geno.options.log_file,
                                                Geno.options.verbose )

        #
        # Print header in log
        #
        printheader( argvs[ 0 ], Geno.options )

        #
        # Parse system and job config file
        #
        Geno.conf = ge_cfg( config_file = Geno.options.config_file, log = log )
        Geno.job = ge_job( Geno.options.job_file, log = log )

        #
        # Prepare directory tree for pipeline to run.
        # Copy the input configuration files to results directory
        #
        if not Geno.options.fullpath:
            os.chdir( '.' )
        make_directories( )
        copy_config_files( )


        #######################################################################
        #
        # Run the defined pipeline
        #

        #
        # Initalize RunTask object
        #
        Geno.RT = RunTask( enable_mpi = Geno.options.mpi, log = log, ncpus = Geno.options.jobs )

        #
        # Get the list of starting files
        #
        log.info( '# main: process={num}'.format( num = Geno.options.jobs ) )

        #
        # Figure out what to run from job configuration file
        #
        job_tasks = Geno.job.get( 'tasks' )

        if True:
            if job_tasks[ 'WGS' ]:
                import wgs_pipeline as pipeline

            elif job_tasks[ 'WES' ]:
                import wes_pipeline as pipeline

            elif job_tasks[ 'Capture' ]:
                import capture_pipeline as pipeline

            pipeline_run(   target_tasks = [ pipeline.last_function ],
                            multiprocess = Geno.options.jobs,
                            logger = log,
                            verbose = Geno.options.verbose )
                            

        #
        #######################################################################

    except IOError as (errno, strerror):
        log.error( "main: I/O error({0}): {1}".format(errno, strerror) )

    except ValueError:
        log.error( "main: ValueError" )

    except:
        exc_info = sys.exc_info()
        if log:
            log.error( "main: Unexpected error:" )

    return 0


################################################################################
if __name__ == "__main__":
    main()
