#! /usr/bin/env python

from genomon_pipeline.run import *
import argparse

parser = argparse.ArgumentParser(prog = "genomon_pipeline")

parser.add_argument("--version", action = "version", version = "genomon_pipeline-2.0.0")

parser.add_argument('analysis_type', choices=['dna', 'rna'],
                    help = "analysis type")

parser.add_argument("sample_conf_file", metavar = "sample_conf.txt", default = None, type = str,
                    help = "input sample list flie [csv/tsv/xlsx]")

parser.add_argument("project_root", metavar = "project_root_dir", default = None, type = str,
                    help = "output root directory")

parser.add_argument("genomon_conf_file", help = "config file for genomon pipeline", type = str)
parser.add_argument("task_conf_file", help = "config file for each task", type = str)

args = parser.parse_args()

main(args)
