#! /usr/bin/python
"""

This is a template of Python main module.


"""

import sys
from datetime import datetime
import argparse

#
# Subroutines
#

def PrintHeader():
    now = datetime.now()

    print '#' * 84
    print '# Summary'
    print '# Generated by %(my)s' % { 'my': myself }
    print '# %(y)d.%(m)d.%(d)d.%(h)d:%(m)d' % { 'y': now.year, 'm': now.month, 'd': now.day, 'h': now.hour, 'm': now.minute }
    print '#' * 84 + ''



def Excel2TSV(ExcelFile, SheetName, TSVFile):
     import xlrd
     workbook = xlrd.open_workbook(ExcelFile)
     worksheet = workbook.sheet_by_name(SheetName)
     tsvfile = open(TSVFile, 'wb')

     for rownum in xrange(worksheet.nrows):
         data_to_write = []
         for x in worksheet.row_values(rownum):
             if isinstance( x, basestring ):
                 x = x.replace( "\t", "")
             if type( x ) == type( u'' ):
                 data_to_write.append( x.encode('utf-8') )
             else:
                 data_to_write.append( str( x ) )

         tsvfile.write( '\t'.join( data_to_write ) + '\n' )

#         wr.writerow(
#             list(x.encode('utf-8') if type(x) == type(u'') else x
#                  for x in worksheet.row_values(rownum)))

     tsvfile.close()


#
# Main
#
if __name__ == "__main__":
  
#
# Argument parse
#
    argvs = sys.argv
    myself = argvs[ 0 ]
    argc = len(argvs)

    parser = argparse.ArgumentParser( description = "Template" )
    parser.add_argument( '-x', '--excel_file', help = "Excel file", type = str )
    parser.add_argument( '-t', '--tsv_file', help = "TSV file", type = str )

    if argc < 5:
        print parser.print_help();
        sys.exit( 1 )
    
    arg = parser.parse_args()

#
# Print header
#
    PrintHeader()

    Excel2TSV( arg.excel_file, 'data', arg.tsv_file )

